# Amazon Reviews Rating Prediction Model

## Importing the Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing Datasets

In [2]:
dataframe_pure = pd.read_csv('Datafiniti_Amazon_Consumer_Reviews_of_Amazon_Products_May19.csv.gz', compression='gzip')

In [3]:
dataframe_pure[:10].style

In [4]:
dataframe = dataframe_pure[['reviews.rating', 'reviews.text']]

In [5]:
dataframe[:100].style

In [6]:
y = dataframe.iloc[:, :-1].values
X = dataframe.iloc[:, -1].values

In [7]:
X = [[len(d)] for d in X]

In [8]:
y = np.ravel(y)
y

array([3, 4, 5, ..., 5, 5, 4])

In [9]:
X = np.asarray(X)
X

array([[139],
       [ 67],
       [ 56],
       ...,
       [317],
       [241],
       [315]])

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [11]:
#### Feature Scale X
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [12]:
X_train

array([[300],
       [ 73],
       [ 70],
       ...,
       [ 45],
       [100],
       [ 65]])

In [13]:
y_train

array([5, 5, 4, ..., 5, 5, 5])

### MSE Function

In [14]:
def MSE(labels, predictions):
    differences = [(x-y)**2 for x,y in zip(predictions,labels)]
    return sum(differences) / len(differences)

### Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 42)
lr_classifier.fit(X_train_scaled, y_train)

LogisticRegression(random_state=42)

In [16]:
y_pred = lr_classifier.predict(X_test_scaled)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0    0    0    3  182]
 [   0    0    0    0  140]
 [   0    0    0    3  251]
 [   0    2    0    7 1084]
 [   1    0    0   13 3981]]


0.7037233103935062

In [18]:
mse = MSE(y_test, y_pred)
mse

1.1164637374272102

### K Nearest Neighbours

In [19]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_classifier.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [20]:
y_pred = knn_classifier.predict(X_test_scaled)

In [21]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  16    2    2   27  138]
 [   2    3    2   33  100]
 [   5    2    7   35  205]
 [   9    8   11  229  836]
 [  19    4   11  616 3345]]


0.6352567496029645

In [22]:
mse = MSE(y_test, y_pred)
mse

1.1176989588847714

### Support Vector Machine

In [23]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'linear', random_state = 42)
svm_classifier.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

In [24]:
y_pred = svm_classifier.predict(X_test_scaled)

In [25]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0    0    0    0  185]
 [   0    0    0    0  140]
 [   0    0    0    0  254]
 [   0    0    0    0 1093]
 [   0    0    0    0 3995]]


0.7049585318510676

In [26]:
mse = MSE(y_test, y_pred)
mse

1.1168166578436562

### Kernel SVM

In [27]:
kernel_classifier = SVC(kernel = 'rbf', random_state = 42)
kernel_classifier.fit(X_train_scaled, y_train)

SVC(random_state=42)

In [28]:
y_pred = kernel_classifier.predict(X_test_scaled)

In [29]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0    0    0    0  185]
 [   0    0    0    0  140]
 [   0    0    0    0  254]
 [   0    0    0    2 1091]
 [   0    0    0    0 3995]]


0.7053114522675137

In [30]:
mse = MSE(y_test, y_pred)
mse

1.1164637374272102

### Naive Bayes

In [31]:
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(X_train_scaled, y_train)

GaussianNB()

In [32]:
y_pred = nb_classifier.predict(X_test_scaled)

In [33]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0    0    0   17  168]
 [   0    0    0   11  129]
 [   0    0    0   11  243]
 [   0    0    0   66 1027]
 [   0    0    0  114 3881]]


0.6964884418563614

In [34]:
mse = MSE(y_test, y_pred)
mse

1.0887594847361919

In [35]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
dt_classifier.fit(X_train_scaled, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=42)

In [36]:
y_pred = dt_classifier.predict(X_test_scaled)

In [37]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  14    2    2   15  152]
 [   2    3    2    9  124]
 [   2    2    7    8  235]
 [   8    7    8   75  995]
 [  12    9   13   91 3870]]


0.7003705664372684

In [38]:
mse = MSE(y_test, y_pred)
mse

1.095817893065114

### Random Forest

In [39]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
rf_classifier.fit(X_train_scaled, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [40]:
y_pred = rf_classifier.predict(X_test_scaled)

In [41]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  12    3    1   16  153]
 [   3    4    1    8  124]
 [   2    1    3   13  235]
 [   6    7    6   71 1003]
 [  12    8    8   91 3876]]


0.6998411858125992

In [42]:
mse = MSE(y_test, y_pred)
mse

1.092465149108876

## Conclusion

Using only review length to predict ratings, we currently only get 70 percent accuracy and around 1.2 MSE with classifiers. Perhaps adding more features (Brands for example, using one hot encoding) may increase the accuracy. 

An interesting project to undertake (if there is an data for it) would be predicting fake reviews on Amazon. The hypothesis is with a review rating of 1 or 5 and short review length, there maybe higher chance of a fake review.